handlers:
  - changed-files:
      - any-glob-to-any-file:
          - http-service/*/src/handlers/**

middlewares:
  - changed-files:
      - any-glob-to-any-file:
          - http-service/*/src/middlewares/**

database:
  - changed-files:
      - any-glob-to-any-file:
          - http-service/*/src/storage/postgres/**
          - http-service/*/include/postgres/**

redis:
  - changed-files:
      - any-glob-to-any-file:
          - http-service/*/src/storage/redis/**
          - http-service/*/include/redis/**

docker:
  - changed-files:
      - any-glob-to-any-file:
          - http-service/*/Dockerfile
          - docker-compose*.yml
          - http-service/*/.dockerignore

api-docs:
  - changed-files:
      - any-glob-to-any-file:
          - http-service/*/docs/**

ci:
  - changed-files:
      - any-glob-to-any-file: .github/**

infra:
  - changed-files:
      - any-glob-to-any-file:
          - http-service/*/src/infra/**

scripts:
  - changed-files:
      - any-glob-to-any-file: scripts/**

auth-server:
  - changed-files:
      - any-glob-to-any-file: http-service/auth-server/**

http-server:
  - changed-files:
      - any-glob-to-any-file: http-service/http-server/**

core:
  - changed-files:
      - any-glob-to-any-file:
          - http-service/*/src/main.c
          - http-service/*/src/httpx.c
          - http-service/*/src/routes/**
          - http-service/*/include/**
