max_connections = 2000

shared_buffers = 25% RAM
effective_cache_size = 70-75% RAM
work_mem = 4MB
wal_buffers = 16MB
random_page_cost = 1.1 (HDD:4)

autovacuum = on
autovacuum_max_workers = 5
autovacuum_naptime = 1min
autovacuum_vacuum_cost_limit = 500

synchronous_commit = off
