CREATE TABLE IF NOT EXISTS user_actives (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT (timezone('UTC', now())),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT (timezone('UTC', now())),
    user_uid BIGINT NOT NULL UNIQUE REFERENCES user_cores(user_uid) ON DELETE CASCADE
);

CREATE OR REPLACE FUNCTION set_updated_at_user_actives()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_updated_at_user_actives_trigger
    BEFORE UPDATE ON user_actives
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at_user_actives();

-- DROP TRIGGER IF EXISTS set_updated_at_user_actives_trigger ON user_actives;
-- DROP FUNCTION IF EXISTS set_updated_at_user_actives();
-- DROP TABLE IF EXISTS user_actives;