CREATE TABLE IF NOT EXISTS chat_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT (timezone('UTC', now())),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT (timezone('UTC', now())),
    user_uid BIGINT NOT NULL,
    name VARCHAR(20) NOT NULL
);

CREATE OR REPLACE FUNCTION set_updated_at_chat_groups()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_updated_at_chat_groups_trigger
    BEFORE UPDATE ON chat_groups
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at_chat_groups();

-- DROP TRIGGER IF EXISTS set_updated_at_chat_groups_trigger ON chat_groups;
-- DROP FUNCTION IF EXISTS set_updated_at_chat_groups();
-- DROP TABLE IF EXISTS chat_groups;