CREATE TABLE IF NOT EXISTS chat_group_user_chats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_uid BIGINT NOT NULL,
    group_id BIGINT NOT NULL,
    chat_id BIGINT NOT NULL,

    CONSTRAINT fk_user FOREIGN KEY (user_uid) REFERENCES user_cores(user_uid) ON DELETE CASCADE,
    CONSTRAINT fk_group FOREIGN KEY (group_id) REFERENCES chat_groups(id) ON DELETE CASCADE,
    CONSTRAINT fk_chat FOREIGN KEY (chat_id) REFERENCES chats(id) ON DELETE CASCADE,

    CONSTRAINT unique_chat_group_user_chat UNIQUE (user_uid, group_id, chat_id)
);

-- DROP TABLE IF EXISTS chat_group_user_chats;