CREATE TABLE user_blocks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_uid BIGINT NOT NULL REFERENCES user_cores(user_uid) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    blocked_until TIMESTAMPTZ,
    reason TEXT NOT NULL,
    blocked_by_uid BIGINT REFERENCES user_cores(user_uid) ON DELETE SET NULL,
    revoked_at TIMESTAMPTZ,
    revoked_by_uid BIGINT REFERENCES user_cores(user_uid) ON DELETE SET NULL,
    revoke_reason TEXT,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,

    CONSTRAINT chk_user_blocks_until
        CHECK (blocked_until IS NULL OR blocked_until > created_at),
    CONSTRAINT chk_user_blocks_reason
        CHECK (length(btrim(reason)) > 0),
    CONSTRAINT chk_user_blocks_revoked_at
        CHECK (revoked_at IS NULL OR revoked_at >= created_at),
    CONSTRAINT chk_user_blocks_revoke_reason
        CHECK (revoke_reason IS NULL OR length(btrim(revoke_reason)) > 0)
);

CREATE INDEX idx_user_blocks_active_user
    ON user_blocks (user_uid, blocked_until)
    WHERE revoked_at IS NULL;

CREATE INDEX idx_user_blocks_created_at
    ON user_blocks (created_at DESC);
