#!/bin/bash

############################################
# Этот bash-скрипт предназначен для подготовки
# кода к deploy, а именно проверяет размер файлов
# заменяет локальные данные на внешний IP
############################################

set -e

# COLORS
GREEN='\033[0;32m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m'

HOME="$(git rev-parse --show-toplevel)"
FILE_C="http-service/http-server/src/main.c"
AUTH_FILE_C="http-service/auth-server/src/main.c"

cd "$HOME"
echo -e "${BLUE}Замена env_init(\".env\") на env_init(\".env.production\")${NC}"
for FILE_C_TARGET in "$FILE_C" "$AUTH_FILE_C"; do
    if sed -i.bak 's/env_init("\.env")/env_init(".env.production")/' "$FILE_C_TARGET"; then
        echo -e "Значение переменной env_init() заменено на env_init(\".env.production\") в $FILE_C_TARGET"
    else
        echo -e "Ошибка: Не удалось заменить значение в файле $FILE_C_TARGET."
        exit 1
    fi
done