CREATE TABLE IF NOT EXISTS message_statuses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id BIGINT REFERENCES messages(id) ON DELETE CASCADE,
    receiver_uid BIGINT NOT NULL REFERENCES user_cores(user_uid) ON DELETE CASCADE,
    delivered_at TIMESTAMPTZ NOT NULL DEFAULT (timezone('UTC', now())),
    read_at TIMESTAMPTZ -- Если есть запись, тогда клиент прочитал сообщение
);

-- DROP TABLE IF EXISTS message_statuses;