CREATE TABLE IF NOT EXISTS message_edits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id BIGINT REFERENCES messages(id) ON DELETE CASCADE,
    old_content TEXT,
    new_content TEXT,
    editor_uid BIGINT REFERENCES user_cores(user_uid) ON DELETE SET NULL,
    edited_at TIMESTAMPTZ NOT NULL DEFAULT (timezone('UTC', now()))
);

-- DROP TABLE IF EXISTS message_edits;