CREATE TABLE IF NOT EXISTS moderation_violations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    user_uid BIGINT NOT NULL REFERENCES user_cores(user_uid) ON DELETE CASCADE,
    reporter_uid BIGINT REFERENCES user_cores(user_uid) ON DELETE SET NULL,
    target_type VARCHAR(32) NOT NULL,
    target_id BIGINT NOT NULL,
    content_fingerprint CHAR(32) NOT NULL,
    content_ref TEXT NOT NULL,
    detector VARCHAR(32) NOT NULL DEFAULT 'nsfw',

    CONSTRAINT chk_moderation_violations_target_type
        CHECK (target_type IN ('avatar', 'chat_media')),
    CONSTRAINT chk_moderation_violations_target_id
        CHECK (target_id > 0),
    CONSTRAINT uq_moderation_violations_target_version
        UNIQUE (target_type, target_id, content_fingerprint)
);

CREATE TABLE IF NOT EXISTS moderation_user_stats (
    user_uid BIGINT PRIMARY KEY REFERENCES user_cores(user_uid) ON DELETE CASCADE,
    violation_count BIGINT NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT chk_moderation_user_stats_count CHECK (violation_count >= 0)
);

CREATE INDEX IF NOT EXISTS idx_moderation_violations_user_created
    ON moderation_violations (user_uid, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_moderation_violations_created
    ON moderation_violations (created_at DESC);
