CREATE TABLE IF NOT EXISTS chat_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT (timezone('UTC', now())),
    chat_id BIGINT REFERENCES chats(id) ON DELETE CASCADE,
    user_uid BIGINT REFERENCES user_cores(user_uid) ON DELETE CASCADE,
    role VARCHAR(16) DEFAULT 'member' CHECK (role IN ('owner', 'admin', 'member')),

    UNIQUE (chat_id, user_uid)
);

-- DROP TABLE IF EXISTS chat_members;