name: CI
on:
    push:
        branches:
            - main
    pull_request:
        branches: ['**']

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    http_server_lint:
        name: Lint http server
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install Go
              uses: actions/setup-go@v5
              with:
                  go-version: '1.24.0'

            - name: Install dependencies
              run: |
                  go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
                  go install golang.org/x/tools/cmd/goimports@latest

            - name: Go mod tidy & download
              run: |
                  go mod tidy && go mod download

            - name: Check imports
              run: |
                  goimports -l .
                  exit 1

            - name: Lint code
              run: |
                  make lint

    http_server_build:
        name: Build binary http server
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install Go
              uses: actions/setup-go@v5
              with:
                  go-version: '1.24.0'

            - name: Build binary
              run: |
                  mkdir -p bin
                  make build

    http_server_tests:
        name: Tests http server
        runs-on: ubuntu-latest
        needs: [http_server_build]
        steps:
            - uses: actions/checkout@v4
            - name: Install Go
              uses: actions/setup-go@v5
              with:
                  go-version: '1.24.0'

            - name: Tested code
              run: |
                  make test

    deploy_prod:
        name: Deploy production
        runs-on: ubuntu-latest
        needs: [http_server_build, http_server_tests]
        if: github.ref == 'refs/heads/main'
        steps:
            - uses: actions/checkout@v3
            - name: SSH Deploy
              uses: appleboy/ssh-action@v0.1.10
              with:
                  host: ${{ secrets.VPS_HOST }}
                  username: ${{ secrets.VPS_USER }}
                  password: ${{ secrets.VPS_PASSWORD }}
                  port: 22
                  script: |
                      set -e

                      cd ./parmigiano-http

                      git stash
                      git checkout main
                      git pull origin main

                      cd ./scripts

                      bash pre_deploy
                      bash systemd
